server:
  port: 8080

spring:
  application:
    name: inflearn
  datasource:
    url: jdbc:mysql://localhost:3306/springbatch?characterEncoding=UTF-8&serverTimezone=UTC&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true