spring:
  batch:
    job:
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: embedded
  datasource:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      data-locations: classpath:person.sql
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: false